name: Azure ML Pipeline
on:
  push:
    branches: [main]

jobs:
  execute-pipeline:
    runs-on: ubuntu-latest
    env:
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      WORKSPACE_NAME: ${{ secrets.WORKSPACE_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install azure-ai-ml azure-identity
          
      - name: Azure Login with Managed Identity
        run: |
          az login --identity
          az account set --subscription $SUBSCRIPTION_ID
          
      - name: Debug Environment Variables
        run: |
          echo "SUBSCRIPTION_ID: $SUBSCRIPTION_ID"
          echo "RESOURCE_GROUP: $RESOURCE_GROUP" 
          echo "WORKSPACE_NAME: $WORKSPACE_NAME"
          
      - name: Execute Pipeline
        run: |
          python scripts/trigger_pipeline.py
